"""initial_order_tables

Revision ID: 1e7f3af72cfa
Revises: 
Create Date: 2026-05-17 12:07:14.872421

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1e7f3af72cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus', schema='orders'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_orders_id'), 'orders', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_orders_status'), 'orders', ['status'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False, schema='orders')
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_order_items_id'), 'order_items', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_items_order_id'), table_name='order_items', schema='orders')
    op.drop_index(op.f('ix_orders_order_items_id'), table_name='order_items', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_status'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_id'), table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    # ### end Alembic commands ###
