"""add_fk_refresh_tokens_user_id

Revision ID: 0695d1b3dbd3
Revises: c8246c85472b
Create Date: 2026-05-17 12:26:13.386190

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0695d1b3dbd3'
down_revision: Union[str, None] = 'c8246c85472b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='users', referent_schema='users', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', schema='users', type_='foreignkey')
    # ### end Alembic commands ###
