"""add_role_to_users

Revision ID: a22112d769e4
Revises: 0695d1b3dbd3
Create Date: 2026-05-24 16:07:03.717656

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a22112d769e4'
down_revision: Union[str, None] = '0695d1b3dbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False), schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role', schema='users')
    # ### end Alembic commands ###
