"""initial_user_tables

Revision ID: c8246c85472b
Revises: 
Create Date: 2026-05-17 12:06:07.162113

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c8246c85472b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True, schema='users')
    op.create_index(op.f('ix_users_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='users')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_id'), 'users', ['id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_id'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    op.drop_index(op.f('ix_users_refresh_tokens_user_id'), table_name='refresh_tokens', schema='users')
    op.drop_index(op.f('ix_users_refresh_tokens_token'), table_name='refresh_tokens', schema='users')
    op.drop_index(op.f('ix_users_refresh_tokens_id'), table_name='refresh_tokens', schema='users')
    op.drop_table('refresh_tokens', schema='users')
    # ### end Alembic commands ###
