"""initial_product_tables

Revision ID: 3970778f143f
Revises: 
Create Date: 2026-05-17 12:06:31.864922

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3970778f143f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='products'
    )
    op.create_index(op.f('ix_products_categories_id'), 'categories', ['id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_categories_slug'), 'categories', ['slug'], unique=True, schema='products')
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['products.categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='products'
    )
    op.create_index(op.f('ix_products_products_category_id'), 'products', ['category_id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_products_id'), 'products', ['id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_products_name'), 'products', ['name'], unique=False, schema='products')
    op.create_index(op.f('ix_products_products_slug'), 'products', ['slug'], unique=True, schema='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_products_slug'), table_name='products', schema='products')
    op.drop_index(op.f('ix_products_products_name'), table_name='products', schema='products')
    op.drop_index(op.f('ix_products_products_id'), table_name='products', schema='products')
    op.drop_index(op.f('ix_products_products_category_id'), table_name='products', schema='products')
    op.drop_table('products', schema='products')
    op.drop_index(op.f('ix_products_categories_slug'), table_name='categories', schema='products')
    op.drop_index(op.f('ix_products_categories_id'), table_name='categories', schema='products')
    op.drop_table('categories', schema='products')
    # ### end Alembic commands ###
