apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
  namespace: shopflow-production
data:
  ENVIRONMENT: "production"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "shopflow"
  POSTGRES_USER: "shopflow"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  USER_SERVICE_URL: "http://user-service:8000"
  PRODUCT_SERVICE_URL: "http://product-service:8000"
  ORDER_SERVICE_URL: "http://order-service:8000"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
  namespace: shopflow-staging
data:
  ENVIRONMENT: "staging"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "shopflow"
  POSTGRES_USER: "shopflow"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  USER_SERVICE_URL: "http://user-service:8000"
  PRODUCT_SERVICE_URL: "http://product-service:8000"
  ORDER_SERVICE_URL: "http://order-service:8000"
  LOG_LEVEL: "DEBUG"
