apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow-production
type: Opaque
stringData:
  POSTGRES_PASSWORD: "shopflow_secret"
  SECRET_KEY: "local-dev-secret-key-for-minikube-only"
  REDIS_URL: "redis://redis-service:6379/0"
  DATABASE_URL: "postgresql+asyncpg://shopflow:shopflow_secret@postgres-service:5432/shopflow"
